<?php
/* array structured for filter-dropdown-options */
return [
    "contactFilters" => [
        [
            "key"=> "available_lead_title",
            "id"=> "available_lead_title",
            "title"=> "Title",
            "value"=> "title",
            "label"=> "Title",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "lookup",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_firstname",
            "id"=> "available_lead_firstname",
            "title"=> "First Name",
            "value"=> "firstname",
            "label"=> "First Name",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_lastname",
            "id"=> "available_lead_lastname",
            "title"=> "Last Name",
            "value"=> "lastname",
            "label"=> "Last Name",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_email",
            "id"=> "available_lead_email",
            "title"=> "Email",
            "value"=> "email",
            "label"=> "Email",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "email",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_mobile",
            "id"=> "available_lead_mobile",
            "title"=> "Mobile",
            "value"=> "mobile",
            "label"=> "Mobile",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "tel",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        /*[
            "key"=> "available_lead_phone",
            "id"=> "available_lead_phone",
            "title"=> "Phone",
            "value"=> "phone",
            "label"=> "Phone",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "tel",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],*/ 
        [
            "key"=> "available_lead_address1",
            "id"=> "available_lead_address1",
            "title"=> "Address Line 1",
            "value"=> "address1",
            "label"=> "Address Line 1",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "including"=> "in",
                "excluding"=> "!in",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_address2",
            "id"=> "available_lead_address2",
            "title"=> "Address Line 2",
            "value"=> "address2",
            "label"=> "Address Line 2",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "including"=> "in",
                "excluding"=> "!in",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_city",
            "id"=> "available_lead_city",
            "title"=> "City",
            "value"=> "city",
            "label"=> "City",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "including"=> "in",
                "excluding"=> "!in",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_state",
            "id"=> "available_lead_state",
            "title"=> "State",
            "value"=> "state",
            "label"=> "State",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "region",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","including"=>"in","excluding"=>"!in","regexp"=>"regexp","not regexp"=>"!regexp"
            ]
        ],
        [
            "key"=> "available_lead_country",
            "id"=> "available_lead_country",
            "title"=> "Country",
            "value"=> "country",
            "label"=> "Country",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "country",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "including"=> "in",
                "excluding"=> "!in",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp"
            ]
        ],
        [
            "key"=> "available_lead_zipcode",
            "id"=> "available_lead_zipcode",
            "title"=> "Zip Code",
            "value"=> "zipcode",
            "label"=> "Zip Code",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","including"=>"in","excluding"=>"!in","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],
        /*[
            "key"=> "available_lead_attribution",
            "id"=> "available_lead_attribution",
            "title"=> "Attribution",
            "value"=> "attribution",
            "label"=> "Attribution",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "number",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "greater than"=> ">",
                "greater than or equal"=> ">=",
                "less than"=> "<",
                "less than or equal"=> "<=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_attribution_date",
            "id"=> "available_lead_attribution_date",
            "title"=> "Attribution Date",
            "value"=> "attribution_date",
            "label"=> "Attribution Date",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "datetime",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "greater than"=> ">",
                "greater than or equal"=> ">=",
                "less than"=> "<",
                "less than or equal"=> "<=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],*/
        [
            "key"=> "available_lead_date_added",
            "id"=> "available_lead_date_added",
            "title"=> "Date Added",
            "value"=> "date_added",
            "label"=> "Date Added",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "date",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "greater than"=> ">",
                "greater than or equal"=> ">=",
                "less than"=> "<",
                "less than or equal"=> "<=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        /*[
            "key"=> "available_lead_date_identified",
            "id"=> "available_lead_date_identified",
            "title"=> "Date Identified",
            "value"=> "date_identified",
            "label"=> "Date Identified",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "date",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "greater than"=> ">",
                "greater than or equal"=> ">=",
                "less than"=> "<",
                "less than or equal"=> "<=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_last_active",
            "id"=> "available_lead_last_active",
            "title"=> "Date Last Active",
            "value"=> "last_active",
            "label"=> "Date Last Active",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "datetime",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "greater than"=> ">",
                "greater than or equal"=> ">=",
                "less than"=> "<",
                "less than or equal"=> "<=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_generated_email_domain",
            "id"=> "available_lead_generated_email_domain",
            "title"=> "Email Domain",
            "value"=> "generated_email_domain",
            "label"=> "Email Domain",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "email_domain",
            "dataFieldOperators"=> [
                "equals"=> "=",
                "not equal"=> "!=",
                "empty"=> "empty",
                "not empty"=> "!empty",
                "like"=> "like",
                "not like"=> "!like",
                "regexp"=> "regexp",
                "not regexp"=> "!regexp",
                "starts with"=> "startsWith",
                "ends with"=> "endsWith",
                "contains"=> "contains"
            ]
        ],
        [
            "key"=> "available_lead_foursquare",
            "id"=> "available_lead_foursquare",
            "title"=> "Foursquare",
            "value"=> "foursquare",
            "label"=> "Foursquare",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_instagram",
            "id"=> "available_lead_instagram",
            "title"=> "Instagram",
            "value"=> "instagram",
            "label"=> "Instagram",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_date_modified",
            "id"=> "available_lead_date_modified",
            "title"=> "Modified Date",
            "value"=> "date_modified",
            "label"=> "Modified Date",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "datetime",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "greater than"=>">",
                "greater than or equal"=>">=",
                "less than"=>"<",
                "less than or equal"=>"<=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_owner_id",
            "id"=> "available_lead_owner_id",
            "title"=> "Owner",
            "value"=> "owner_id",
            "label"=> "Owner",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "lookup_id",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty"
            ]
        ], 
        [
            "key"=> "available_lead_points",
            "id"=> "available_lead_points",
            "title"=> "Points (+/-)",
            "value"=> "points",
            "label"=> "Points (+/-)",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "number",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "greater than"=>">",
                "greater than or equal"=>">=",
                "less than"=>"<",
                "less than or equal"=>"<=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_position",
            "id"=> "available_lead_position",
            "title"=> "Position",
            "value"=> "position",
            "label"=> "Position",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_preferred_locale",
            "id"=> "available_lead_preferred_locale",
            "title"=> "Preferred Locale",
            "value"=> "preferred_locale",
            "label"=> "Preferred Locale",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "locale",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp"
            ]
        ],
        [
            "key"=> "available_lead_timezone",
            "id"=> "available_lead_timezone",
            "title"=> "Preferred Timezone",
            "value"=> "timezone",
            "label"=> "Preferred Timezone",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "timezone",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp"
            ]
        ],
        [
            "key"=> "available_lead_company",
            "id"=> "available_lead_company",
            "title"=> "Primary Company",
            "value"=> "company",
            "label"=> "Primary Company",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=",
                "not equal"=>"!=",
                "empty"=>"empty",
                "not empty"=>"!empty",
                "like"=>"like",
                "not like"=>"!like",
                "including"=>"in",
                "excluding"=>"!in",
                "regexp"=>"regexp",
                "not regexp"=>"!regexp",
                "starts with"=>"startsWith",
                "ends with"=>"endsWith",
                "contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_skype",
            "id"=> "available_lead_skype",
            "title"=> "Skype",
            "value"=> "skype",
            "label"=> "Skype",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","including"=>"in","excluding"=>"!in","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_stage",
            "id"=> "available_lead_stage",
            "title"=> "Stage",
            "value"=> "stage",
            "label"=> "Stage",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "stage",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty"
            ]
        ],*/
        [
            "key"=> "available_lead_tags",
            "id"=> "available_lead_tags",
            "title"=> "Tags",
            "value"=> "tags",
            "label"=> "Tags",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "tags",
            "dataFieldOperators"=>[
                "empty"=>"empty","not empty"=>"!empty","including"=>"in","excluding"=>"!in"
            ]
        ],
        /*[
            "key"=> "available_lead_twitter",
            "id"=> "available_lead_twitter",
            "title"=> "Twitter",
            "value"=> "twitter",
            "label"=> "Twitter",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","including"=>"in","excluding"=>"!in","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_website",
            "id"=> "available_lead_website",
            "title"=> "Website",
            "value"=> "website",
            "label"=> "Website",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "url",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],
        [
            "key"=> "available_lead_linkedin",
            "id"=> "available_lead_linkedin",
            "title"=> "Linkedin",
            "value"=> "linkedin",
            "label"=> "Linkedin",
            "className"=> "segment-filter user",
            "function"=> "",
            "dataFieldObject"=> "contact",
            "dataFieldType"=> "text",
            "dataFieldOperators"=>[
                "equals"=>"=","not equal"=>"!=","empty"=>"empty","not empty"=>"!empty","like"=>"like","not like"=>"!like","including"=>"in","excluding"=>"!in","regexp"=>"regexp","not regexp"=>"!regexp","starts with"=>"startsWith","ends with"=>"endsWith","contains"=>"contains"
            ]
        ],*/
    ]
];

